# Generated by Django 5.0.1 on 2024-03-03 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=600)),
                ('amount', models.CharField(max_length=600)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rememberApp.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
